### ISSUE TITLE
Flags enum value incorrectly combines the 'All' value

### ISSUE THREAD

**Issue by jnm2** [PublicApiGenerator/PublicApiGenerator#214]
Source:
```cs
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
```

Generated in 10.2.0:
```cs
[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.All, Inherited=false)]
```

**Comment by stakx** [comment]
This appears to be caused here:

https://github.com/PublicApiGenerator/PublicApiGenerator/blob/7e11cac7cb87e2c27e73b792a1c20d2ea4af3b23/src/PublicApiGenerator/ApiGenerator.cs#L536-L540

This will select all enum values that have _at least one_ of their bits set (`(originalValue & v) != 0`), instead of selecting only those that have _all_ of their bits set (`(originalValue & v) == v`).
