### ISSUE TITLE
Question about System.AttributeTargets.All

### ISSUE THREAD

**Issue by sungam3r** [PublicApiGenerator/PublicApiGenerator#233]
See https://github.com/graphql-dotnet/graphql-dotnet/pull/2879/files#r790776863

I can not understand what is happening. For some reason I see `System.AttributeTargets.All` appended to all attributes.

**Comment by Shane32** [comment]
Probably fixed in #215 which has not been released yet.

**Comment by sungam3r** [comment]
WOW! @stakx Maybe it's time to publish a release? The last 10.2 was over 18 months ago.

**Comment by stakx** [comment]
@sungam3r, absolutely. I have been crazy busy with work for the past 6 months. Sorry for the delay.

**Comment by stakx** [comment]
> Maybe it's time to publish a release?

Done. Finally. Sorry again for the delay.

**Comment by sungam3r** [comment]
👍

**Comment by stakx** [comment]
> For some reason I see `System.AttributeTargets.All` appended to all attributes.

@Shane32 was on the right track, like I mentioned back in https://github.com/PublicApiGenerator/PublicApiGenerator/pull/215:

Should the emitted API for `Test` mention only `[Letters(Letters.All)]`, or `[Letters(Letters.A | Letters.B | Letters.AB | Letters.All)]`? Perhaps the [former], as `All` encompasses all other flags and results in terser output. Finding the minimal set of flags might be quite tricky (or at least computationally more expensive), so I'm leaving that to a future PR for now.

Meaning, finding a more minimal set of flags enum options hasn't happened yet, therefore instead of simply `AttributeTargets.All` you get a list of them all... which isn't incorrect, but simply way more verbose than strictly necessary.

**Comment by sungam3r** [comment]
Thanks. Fixed now.

**Comment by Shane32** [comment]
I don’t think it’s a matter of finding the most minimal set of flags that’s the problem so much as being accurate. I wouldn’t mind duplicate flags so long as it was still accurate. But having “All” in the list is inaccurate.

**Comment by sungam3r** [comment]
Agree. Behavior may be the same as for `Enum.ToString()` for flags enum.

**Comment by stakx** [comment]
> But having “All” in the list is inaccurate.

Could you please elaborate? "Inaccurate" in which sense?
