### ISSUE TITLE
Unexpected ordering on FullName

### ISSUE THREAD

**Issue by jnyrup** [PublicApiGenerator/PublicApiGenerator#389]
When dumping this API, the namespace `A.C` is listed before `A` as we compare the types by `FullName` and `"A.C.B"` comes before `"A.D"`.
```cs
namespace A
{
    public class D;
}

namespace A.C
{
    public class B;
}
```

```
[assembly: System.Runtime.Versioning.TargetFramework(".NETCoreApp,Version=v8.0", FrameworkDisplayName=".NET 8.0")]
namespace A.C
{
    public class B
    {
        public B() { }
    }
}
namespace A
{
    public class D
    {
        public D() { }
    }
}
```

If I then add a new type `A.A`, the dump now lists the namespace `A` before `A.C` as `"A.A"` comes before `"A.C.B"`.

```cs
namespace A
{
    public class A;
}

namespace A
{
    public class D;
}

namespace A.C
{
    public class B;
}
```

```
[assembly: System.Runtime.Versioning.TargetFramework(".NETCoreApp,Version=v8.0", FrameworkDisplayName=".NET 8.0")]
namespace A
{
    public class A
    {
        public A() { }
    }
    public class D
    {
        public D() { }
    }
}
namespace A.C
{
    public class B
    {
        public B() { }
    }
}
```

The real issue for me is not _how_ the types are ordered but that adding a single type to one namespacce will re-order _other_ namespaces, which makes it harder to diff.
As I understand from reading #56 and #138 one goal for this project is to make the output friendly for diffing.
Since GitHub uses the myers diff algorithm, which is not great with moving elements, the diff can be quite confusing.

A suggestion is to create a custom `TypeReference` comparer and first compare by `Namespace` and then by `Name`.
I'm trying that out [here](https://github.com/jnyrup/PublicApiGenerator/tree/jn/type_ordering)
This works for the case above, but I note that `TypeReference.FullName` also looks at `IsNested` and whether `NameSpace` is null or empty - I haven't thought about how this should be compared.

Here's a test to reproduce:
```cs
[Fact]
public void Should_order_namespaces_alphabetically2()
{
    AssertPublicApi(
    [
        typeof(A.D),
        typeof(A.C.B),
    ],
@"namespace PublicApiGeneratorTests.A
{
    public class D
    {
        public D() { }
    }
}
namespace PublicApiGeneratorTests.A.C
{
    public class B
    {
        public B() { }
    }
}");
}

namespace A
{
    public class D;
}

namespace A.C
{
    public class B;
}
```

**Comment by jafaber** [comment]
I haven't tested the exact ordering, but this sounds bad indeed.

To me diffing is the entire point of using this tool. In fact that's why I'm going one step further: I split up the string into multiple files; one per namespace. That way a namespace change in my source code will simply show as a rename of a file with a trivial diff, instead of having whole blocks of code getting shuffled around.

And I'm planning to go to one file per type, possibly in a directory structure reflecting the namespaces. Otherwise I still have the same diff problem when a class gets renamed.

Currently I'm doing it after the fact by splitting up the string, but it would be so much better if PublicApiGenerator would just return a Dictionary<string, string> keyed by the Type.FullName (with a special key for the AssemblyInfo, maybe empty string).

(Sorry for hijacking your post.)

**Comment by jnyrup** [comment]
Please create a separate issue for that instead of hijacking and side-tracking this one.
